export const countriesList = [
	{ value: "AF", label: "Afghanistan" },
	{ value: "EG", label: "Ai Cập" },
	{ value: "AL", label: "Albania" },
	{ value: "DZ", label: "Algeria" },
	{ value: "AS", label: "American Samoa" },
	{ value: "AD", label: "Andorra" },
	{ value: "AO", label: "Angola" },
	{ value: "AI", label: "Anguilla" },
	{ value: "GB", label: "Anh (UK)" },
	{ value: "AQ", label: "Antarctica" },
	{ value: "AG", label: "Antigua và Barbuda" },
	{ value: "AR", label: "Argentina" },
	{ value: "AM", label: "Armenia" },
	{ value: "AW", label: "Aruba" },
	{ value: "AZ", label: "Azerbaijan" },
	{ value: "BS", label: "Bahamas" },
	{ value: "BH", label: "Bahrain" },
	{ value: "BD", label: "Bangladesh" },
	{ value: "BB", label: "Barbados" },
	{ value: "BY", label: "Belarus" },
	{ value: "PW", label: "Belau" },
	{ value: "BZ", label: "Belize" },
	{ value: "BJ", label: "Benin" },
	{ value: "BM", label: "Bermuda" },
	{ value: "BT", label: "Bhutan" },
	{ value: "BO", label: "Bolivia" },
	{ value: "BQ", label: "Bonaire, Saint Eustatius và Saba" },
	{ value: "BA", label: "Bosnia và Herzegovina" },
	{ value: "BW", label: "Botswana" },
	{ value: "BR", label: "Brazil" },
	{ value: "BN", label: "Brunei" },
	{ value: "BG", label: "Bulgaria" },
	{ value: "BF", label: "Burkina Faso" },
	{ value: "BI", label: "Burundi" },
	{ value: "BE", label: "Bỉ" },
	{ value: "PT", label: "Bồ Đào Nha" },
	{ value: "CI", label: "Bờ biển Ngà" },
	{ value: "CM", label: "Cameroon" },
	{ value: "KH", label: "Campuchia" },
	{ value: "CA", label: "Canada" },
	{ value: "CV", label: "Cape Verde" },
	{ value: "TD", label: "Chad" },
	{ value: "CL", label: "Chile" },
	{ value: "CX", label: "Christmas Island" },
	{ value: "CO", label: "Colombia" },
	{ value: "KM", label: "Comoros" },
	{ value: "CG", label: "Congo (Brazzaville)" },
	{ value: "CD", label: "Congo (Kinshasa)" },
	{ value: "CR", label: "Costa Rica" },
	{ value: "HR", label: "Croatia" },
	{ value: "CU", label: "Cuba" },
	{ value: "CW", label: "CuraÇao" },
	{ value: "CY", label: "Cyprus" },
	{ value: "UM", label: "Các Tiểu đảo xa của Hoa Kỳ (US)" },
	{ value: "AE", label: "Các tiểu vương quốc Ả Rập" },
	{ value: "DO", label: "Cộng hòa Dominica" },
	{ value: "CZ", label: "Cộng hòa Séc" },
	{ value: "CF", label: "Cộng hòa Trung Phi" },
	{ value: "DJ", label: "Djibouti" },
	{ value: "DM", label: "Dominica" },
	{ value: "EC", label: "Ecuador" },
	{ value: "SV", label: "El Salvador" },
	{ value: "ER", label: "Eritrea" },
	{ value: "EE", label: "Estonia" },
	{ value: "ET", label: "Ethiopia" },
	{ value: "FJ", label: "Fiji" },
	{ value: "GA", label: "Gabon" },
	{ value: "GM", label: "Gambia" },
	{ value: "GE", label: "Georgia" },
	{ value: "GH", label: "Ghana" },
	{ value: "GI", label: "Gibraltar" },
	{ value: "GL", label: "Greenland" },
	{ value: "GD", label: "Grenada" },
	{ value: "GP", label: "Guadeloupe" },
	{ value: "GU", label: "Guam" },
	{ value: "GT", label: "Guatemala" },
	{ value: "GG", label: "Guernsey" },
	{ value: "GN", label: "Guinea" },
	{ value: "GQ", label: "Guinea Xích đạo" },
	{ value: "GW", label: "Guinea-Bissau" },
	{ value: "GY", label: "Guyana" },
	{ value: "GF", label: "Guyane thuộc Pháp" },
	{ value: "HT", label: "Haiti" },
	{ value: "HN", label: "Honduras" },
	{ value: "HU", label: "Hungary" },
	{ value: "GR", label: "Hy Lạp" },
	{ value: "NL", label: "Hà Lan" },
	{ value: "KR", label: "Hàn Quốc" },
	{ value: "HK", label: "Hồng Kông" },
	{ value: "IS", label: "Iceland" },
	{ value: "ID", label: "Indonesia" },
	{ value: "IR", label: "Iran" },
	{ value: "IQ", label: "Iraq" },
	{ value: "IE", label: "Ireland" },
	{ value: "IL", label: "Israel" },
	{ value: "JM", label: "Jamaica" },
	{ value: "JE", label: "Jersey" },
	{ value: "JO", label: "Jordan" },
	{ value: "KZ", label: "Kazakhstan" },
	{ value: "KE", label: "Kenya" },
	{ value: "KI", label: "Kiribati" },
	{ value: "KW", label: "Kuwait" },
	{ value: "KG", label: "Kyrgyzstan" },
	{ value: "LV", label: "Latvia" },
	{ value: "LB", label: "Lebanon" },
	{ value: "LS", label: "Lesotho" },
	{ value: "LR", label: "Liberia" },
	{ value: "LY", label: "Libya" },
	{ value: "LI", label: "Liechtenstein" },
	{ value: "LT", label: "Lithuania" },
	{ value: "LU", label: "Luxembourg" },
	{ value: "LA", label: "Lào" },
	{ value: "TF", label: "Lãnh thổ miền Nam nước Pháp" },
	{ value: "IO", label: "Lãnh thổ Ấn Độ Dương thuộc Anh" },
	{ value: "MO", label: "Ma Cao" },
	{ value: "MK", label: "Macedonia" },
	{ value: "MG", label: "Madagascar" },
	{ value: "MW", label: "Malawi" },
	{ value: "MY", label: "Malaysia" },
	{ value: "MV", label: "Maldives" },
	{ value: "ML", label: "Mali" },
	{ value: "MT", label: "Malta" },
	{ value: "MQ", label: "Martinique" },
	{ value: "MR", label: "Mauritania" },
	{ value: "MU", label: "Mauritius" },
	{ value: "YT", label: "Mayotte" },
	{ value: "MX", label: "Mexico" },
	{ value: "FM", label: "Micronesia" },
	{ value: "MD", label: "Moldova" },
	{ value: "MC", label: "Monaco" },
	{ value: "ME", label: "Montenegro" },
	{ value: "MS", label: "Montserrat" },
	{ value: "MA", label: "Morocco" },
	{ value: "MZ", label: "Mozambique" },
	{ value: "MM", label: "Myanmar" },
	{ value: "MN", label: "Mông Cổ" },
	{ value: "US", label: "Mỹ (US)" },
	{ value: "NO", label: "Na Uy" },
	{ value: "GS", label: "Nam Georgia và Quần đảo Nam Sandwich" },
	{ value: "ZA", label: "Nam Phi" },
	{ value: "SS", label: "Nam Sudan" },
	{ value: "NA", label: "Namibia" },
	{ value: "NR", label: "Nauru" },
	{ value: "NP", label: "Nepal" },
	{ value: "NC", label: "New Caledonia" },
	{ value: "NZ", label: "New Zealand" },
	{ value: "RU", label: "Nga" },
	{ value: "JP", label: "Nhật Bản" },
	{ value: "NI", label: "Nicaragua" },
	{ value: "NE", label: "Niger" },
	{ value: "NG", label: "Nigeria" },
	{ value: "NU", label: "Niue" },
	{ value: "NF", label: "Norfolk Island" },
	{ value: "OM", label: "Oman" },
	{ value: "PK", label: "Pakistan" },
	{ value: "PS", label: "Palestinian Territory" },
	{ value: "PA", label: "Panama" },
	{ value: "PG", label: "Papua New Guinea" },
	{ value: "PY", label: "Paraguay" },
	{ value: "PE", label: "Peru" },
	{ value: "PH", label: "Philippines" },
	{ value: "FR", label: "Pháp" },
	{ value: "PL", label: "Phần Lan" },
	{ value: "FI", label: "Phần Lan" },
	{ value: "PN", label: "Pitcairn" },
	{ value: "PF", label: "Polynesia thuộc Pháp" },
	{ value: "PR", label: "Puerto Rico" },
	{ value: "QA", label: "Qatar" },
	{ value: "AX", label: "Quần đảo Åland" },
	{ value: "VG", label: "Quần đảo British Virgin" },
	{ value: "MP", label: "Quần đảo Bắc Mariana" },
	{ value: "KY", label: "Quần đảo Cayman" },
	{ value: "CC", label: "Quần đảo Cocos (Keeling)" },
	{ value: "CK", label: "Quần đảo Cook" },
	{ value: "FK", label: "Quần đảo Falkland" },
	{ value: "FO", label: "Quần đảo Faroe" },
	{ value: "MH", label: "Quần đảo Marshall" },
	{ value: "SB", label: "Quần đảo Solomon" },
	{ value: "VI", label: "Quần đảo Virgin của Hoa Kỳ (US)" },
	{ value: "RE", label: "Reunion" },
	{ value: "RO", label: "Romania" },
	{ value: "RW", label: "Rwanda" },
	{ value: "ST", label: "São Tomé và Príncipe" },
	{ value: "BL", label: "Saint Barthélemy" },
	{ value: "SH", label: "Saint Helena" },
	{ value: "KN", label: "Saint Kitts và Nevis" },
	{ value: "LC", label: "Saint Lucia" },
	{ value: "SX", label: "Saint Martin (thuộc Hà Lan)" },
	{ value: "PM", label: "Saint Pierre và Miquelon" },
	{ value: "VC", label: "Saint Vincent và Grenadines" },
	{ value: "MF", label: "Saint-Martin (thuộc Pháp)" },
	{ value: "SM", label: "San Marino" },
	{ value: "SN", label: "Senegal" },
	{ value: "RS", label: "Serbia" },
	{ value: "SC", label: "Seychelles" },
	{ value: "SL", label: "Sierra Leone" },
	{ value: "SG", label: "Singapore" },
	{ value: "SK", label: "Slovakia" },
	{ value: "SI", label: "Slovenia" },
	{ value: "SO", label: "Somalia" },
	{ value: "LK", label: "Sri Lanka" },
	{ value: "SD", label: "Sudan" },
	{ value: "SR", label: "Suriname" },
	{ value: "SJ", label: "Svalbard và Jan Mayen" },
	{ value: "SZ", label: "Swaziland" },
	{ value: "SY", label: "Syria" },
	{ value: "TJ", label: "Tajikistan" },
	{ value: "TZ", label: "Tanzania" },
	{ value: "TH", label: "Thái Lan" },
	{ value: "TR", label: "Thổ Nhĩ Kỳ" },
	{ value: "CH", label: "Thụy Sĩ" },
	{ value: "SE", label: "Thụy Điển" },
	{ value: "TG", label: "Togo" },
	{ value: "TK", label: "Tokelau" },
	{ value: "TO", label: "Tonga" },
	{ value: "TT", label: "Trinidad và Tobago" },
	{ value: "KP", label: "Triều Tiên" },
	{ value: "CN", label: "Trung Quốc" },
	{ value: "TN", label: "Tunisia" },
	{ value: "TM", label: "Turkmenistan" },
	{ value: "TC", label: "Turks và quần đảo Caicos" },
	{ value: "TV", label: "Tuvalu" },
	{ value: "ES", label: "Tây Ban Nha" },
	{ value: "UG", label: "Uganda" },
	{ value: "UA", label: "Ukraine" },
	{ value: "UY", label: "Uruguay" },
	{ value: "UZ", label: "Uzbekistan" },
	{ value: "VU", label: "Vanuatu" },
	{ value: "VA", label: "Vatican" },
	{ value: "VE", label: "Venezuela" },
	{ value: "VN", label: "Việt Nam" },
	{ value: "WF", label: "Wallis và Futuna" },
	{ value: "EH", label: "Western Sahara" },
	{ value: "YE", label: "Yemen" },
	{ value: "ZM", label: "Zambia" },
	{ value: "ZW", label: "Zimbabwe" },
	{ value: "AT", label: "Áo" },
	{ value: "AU", label: "Úc" },
	{ value: "IT", label: "Ý" },
	{ value: "DK", label: "Đan Mạch" },
	{ value: "TW", label: "Đài Loan" },
	{ value: "TL", label: "Đông Timo" },
	{ value: "BV", label: "Đảo Bouvet" },
	{ value: "HM", label: "Đảo Heard và quần đảo McDonald" },
	{ value: "IM", label: "Đảo Man" },
	{ value: "WS", label: "Đảo Samoa" },
	{ value: "DE", label: "Đức" },
	{ value: "SA", label: "Ả Rập Saudi" },
	{ value: "IN", label: "Ấn Độ" },
];
